spring:
  application:
    name: app-ai-crafter
  security:
    user:
      name: user
      password: ${SPRING_SECURITY_PASSWORD}
  datasource:
    url: jdbc:postgresql://localhost:5432/crafter-db
    username: admin
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  ai:
    openai:
      api-key: https://openrouter.ai/api
      chat:
        options:
          model: openai/gpt-5.2-codex
          temperature: 0.0

jwt:
  secret: ${JWT_SECRET}

stripe:
  api:
    secret: ${STRIPE_API_SECRET}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}

client:
  url: http://localhost:8080

